# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47bc5e958f272e93e4079e76c4449609cd90d42fb8517af8f12efa8f9fba8e309fc3b674ebeb74f7adaf727a2b622e98f560fff5e19aef3e8ebaea98a153dc20

test:
  secret_key_base: 4b89308afd2588d9e132e6f6c665e8b36f980e9df69f0122e261e5783298481d6140ad6424c0619fd0cb43113bc380875a9800c6ee3d8bbf61885472c5860b9e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
